### ISSUE TITLE
Pytorch 2.5.0 + Megablocks undefined symbol error

### ISSUE THREAD

**Issue by jramapuram** [databricks/megablocks#159]
Hi there, there seems to be an error with the newer pytorch (I already relaxed the <2.4.1 constraint in setup.py):

```bash
     10 # Wrap this in a try-block with better error message and
     11 # instructions for building the c++ operations.
     12 try:
---> 13     import megablocks_ops as ops  # type: ignore
     14 except ModuleNotFoundError as e:
     15     raise ModuleNotFoundError("No module named 'megablocks_ops'.") from e
...
python3.10/site-packages/megablocks_ops.cpython-310-x86_64-linux-gnu.so: undefined symbol: _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs
```

**Comment by mihir-db** [comment]
Will be bumped soon and we'll have official support then :) 

I've seen this a few times if your environment reinstalls torch when upgrading. My guess is something in the C++ linker messes up... not 100% sure. 

The best way to avoid this is likely to replace cuda kernels with pure triton ops here: https://github.com/databricks/megablocks/tree/main/csrc if you're interested in helping out!

**Comment by jramapuram** [comment]
This was in a fresh build with torch compiled from source for context

**Comment by Birch-san** [comment]
@jramapuram probably your megablocks is attempting to link against a different distribution of torch than the one you compiled.

for example, if setup.py's version constraints downgraded your pytorch, or if build isolation created a separate environment with an off-the-shelf pytorch for you.

the symbol `_ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKSs`, which [demangles](http://demangler.com/) to `c10::detail::torchInternalAssertFail(char const*, char const*, unsigned int, char const*, std::string const&)` **should** exist in pytorch's `libc10.so`, so if it can't be imported then probably your built-from-source pytorch targets the C++11 ABI, whereas off-the-shelf pytorch<2.6 was distributed with an older ABI.

we can verify this:

```
pip show torch
Version: 2.6.0
Location: /usr/local/lib/python3.10/dist-packages
```

my local pytorch's lib10.so has the symbol mentioned in that error, here's how we know:

```
nm /usr/local/lib/python3.10/dist-packages/torch/lib/libc10.so | grep _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_
00000000000a98a0 T _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
00000000000aa43f t _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_RKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE.cold
00000000000a9830 T _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_S2_
00000000000aa41a t _ZN3c106detail23torchInternalAssertFailEPKcS2_jS2_S2_.cold
```

to target a newer version of pytorch, I recommend to build megablocks like so…

modify setup.py:

- comment-out the torch and triton dependencies in `install_requires`
- change `if 'cu' in torch.__version__ and CUDA_HOME is not None:` to just `if CUDA_HOME is not None:`

then build megablocks' wheel like so:

```bash
TORCH_CUDA_ARCH_LIST="9.0" pip install grouped_gemm==0.1.6
pip install -U 'setuptools<70.0.0'
git clone --recurse-submodules -j8 https://github.com/databricks/megablocks.git
cd megablocks
MAX_JOBS=6 \
PIP_NO_BUILD_ISOLATION=1 \
TORCH_CUDA_ARCH_LIST="9.0" \
PYTHONPATH="third_party/Megatron-LM:$PYTHONPATH" \
python setup.py bdist_wheel
```

this should output `dist/megablocks-0.8.0.dev0-cp310-cp310-linux_x86_64.whl`.

you can install the wheel with:

```bash
pip install dist/megablocks-0.8.0.dev0-cp310-cp310-linux_x86_64.whl
```

========

to use megablocks, first `cd` out of the megablocks directory, so that your the local megablocks module doesn't take precedence over your installed packages.

you'll notice that your example doesn't run verbatim:

```
alex@alex-h100-0:~/cwsp/git/megablocks/dist$ ipython
Python 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.32.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: try:
   ...:     import megablocks_ops as ops  # type: ignore
   ...: except ModuleNotFoundError as e:
   ...:     raise ModuleNotFoundError("No module named 'megablocks_ops'.") from e
   ...: 
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 2
      1 try:
----> 2     import megablocks_ops as ops  # type: ignore
      3 except ModuleNotFoundError as e:
      4     raise ModuleNotFoundError("No module named 'megablocks_ops'.") from e

ImportError: libc10.so: cannot open shared object file: No such file or directory
```

let's investigate why the library dependencies of megablocks failed to load.

we can unzip this wheel to see what's inside:

```bash
cd megablocks/dist
unzip megablocks-0.8.0.dev0-cp310-cp310-linux_x86_64.whl
```

we can see which libraries megablocks expresses dynamic links to. some of them are from pytorch.

```
ldd megablocks_ops.cpython-310-x86_64-linux-gnu.so
	linux-vdso.so.1 (0x00007ffc0abea000)
	libc10.so => not found
	libtorch_cpu.so => not found
	libtorch_python.so => not found
	libcudart.so.12 => /usr/local/cuda/targets/x86_64-linux/lib/libcudart.so.12 (0x00007038c5400000)
	libc10_cuda.so => not found
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007038c5193000)
	libgcc_s.so.1 => /usr/lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007038c56d4000)
	libc.so.6 => /usr/lib/x86_64-linux-gnu/libc.so.6 (0x00007038c4f6a000)
	/lib64/ld-linux-x86-64.so.2 (0x00007038c58ec000)
	libdl.so.2 => /usr/lib/x86_64-linux-gnu/libdl.so.2 (0x00007038c56cf000)
	libpthread.so.0 => /usr/lib/x86_64-linux-gnu/libpthread.so.0 (0x00007038c56c8000)
	librt.so.1 => /usr/lib/x86_64-linux-gnu/librt.so.1 (0x00007038c56c3000)
	libm.so.6 => /usr/lib/x86_64-linux-gnu/libm.so.6 (0x00007038c4e83000)
```

okay, so megablocks doesn't say where libc10.so can be found. I think that's down to rpath resolution or something.

so torch is probably meant to load this library for us.

```
ls -l /usr/local/lib/python3.10/dist-packages/torch/lib
-rw-r--r-- 1 root root    1231592 Feb  1 23:11 libc10.so
-rw-r--r-- 1 root root     673056 Feb  1 23:11 libc10_cuda.so
-rw-r--r-- 1 root root      10840 Feb  1 23:11 libcaffe2_nvrtc.so
-rw-r--r-- 1 root root      36864 Feb  1 23:11 libshm.so
-rw-r--r-- 1 root root       5144 Feb  1 23:11 libtorch.so
-rw-r--r-- 1 root root  310885440 Feb  1 23:11 libtorch_cpu.so
-rw-r--r-- 1 root root 1674123704 Feb  1 23:11 libtorch_cuda.so
-rw-r--r-- 1 root root     667544 Feb  1 23:11 libtorch_cuda_linalg.so
-rw-r--r-- 1 root root       5440 Feb  1 23:11 libtorch_global_deps.so
-rw-r--r-- 1 root root   28218136 Feb  1 23:11 libtorch_python.so
```

yup, it's a torch thing.

okay, how about changing the example code to load torch first:

```
alex@alex-h100-0:~/cwsp/git/megablocks/dist$ ipython
Python 3.10.12 (main, Jan 17 2025, 14:35:34) [GCC 11.4.0]
Type 'copyright', 'credits' or 'license' for more information
IPython 8.32.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import torch

In [2]: try:
   ...:     import megablocks_ops as ops  # type: ignore
   ...: except ModuleNotFoundError as e:
   ...:     raise ModuleNotFoundError("No module named 'megablocks_ops'.") from e
   ...: 

In [3]: 
```

yes, works fine.

alternatively, we can import megablocks first:

```
In [1]: import megablocks
/mnt/clusterstorage/workspace/mahouko/git/megablocks/dist/megablocks/grouped_gemm_util.py:10: UserWarning: Grouped GEMM not available.
  warnings.warn('Grouped GEMM not available.')

In [2]: import megablocks_ops
```

hope this helps.

**Comment by jramapuram** [comment]
Thanks for the detailed response @Birch-san  🙏 . This definitely works :) 

I owe you a 🍺 , hope to see you at ICLR this year if you are going!

**Comment by Birch-san** [comment]
certainly up for a drink, I've never been to a conference but if you're around for any events in the UK that's easier for me to get to!
